image: Visual Studio 2017

clone_folder: C:\projects\dramatiq

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

  PROJ: C:\\projects\\dramatiq
  DEPS: C:\\projects\\libs

init:
  - mkdir %DEPS%
  - set APPVEYOR=true

before_build:
  - choco install rabbitmq --ignoredependencies -y
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start

install:
  # Download and start a binary version of memcached.
  - ps: Invoke-WebRequest "https://s3.amazonaws.com/downloads.northscale.com/memcached-win64-1.4.4-14.zip" -OutFile "$ENV:DEPS\memcached.zip"
  - 7z x %DEPS%\memcached.zip -y -o%DEPS%\
  - ps: $Memcached = Start-Process $ENV:DEPS\memcached\memcached.exe -PassThru

  # Download libmemcached sources to use when installing pylibmc.
  - cd %DEPS%
  - git clone --single-branch --branch=x64 https://github.com/ryansm1/libmemcached-win
  - cd %DEPS%\libmemcached-win\win32
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - set INCLUDE=%DEPS%\libmemcached-win;%INCLUDE%
  - msbuild libmemcached.vcxproj /p:UseEnv=true /p:Configuration=Release /t:Build;CopyFiles
  - cp .\Lib\memcached.dll %PROJ%
  - set LMCD_DIR=%cd%

  # Install python and pip.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV% python --version"
  - "%CMD_IN_ENV% python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "%CMD_IN_ENV% python -m pip install --upgrade pip"

  # Install pylibmc
  - '%CMD_IN_ENV% pip install --install-option="--without-zlib" --install-option="--with-libmemcached=%LMCD_DIR%" pylibmc'

  # Install dramatiq
  - cd %PROJ%
  - "%CMD_IN_ENV% pip install -e .[dev]"

build_script:
  - "%CMD_IN_ENV% python setup.py build"

test_script:
  - "%CMD_IN_ENV% py.test --benchmark-skip"

after_test:
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - "%CMD_IN_ENV% python setup.py bdist_wininst"
  - "%CMD_IN_ENV% python setup.py bdist_msi"
  - ps: "ls dist"

on_failure:
  - ps: "Get-Content \"C:\\ProgramData\\chocolatey\\logs\\chocolatey.log\" -Tail 30"
