name: PyPI release

# Note this workflow is designed to be locked-down to prevent supply chain attacks;
# 1. GitHub actions are specified by exact hash.
# 2. Distributions are built in a seperate job to the publishing action.
# 3. No caching is used to prevent cache poisoning.

on:
  release:
    types: [ published ]

jobs:
  package:
    runs-on: ubuntu-latest

    # Don't run in forks in the unlikely event a Release is created there.
    if: github.repository == 'Bogdanp/dramatiq'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install --group build

      - name: Build dist packages
        run: python -m build .

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "dist"
          path: "dist/"

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'Bogdanp/dramatiq'
    needs:
      - package
    environment: pypi # Specifying a GitHub environment is optional, but strongly encouraged
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for Trusted Publishing
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: "dist"
          path: "dist"
      - name: Upload packages to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
